apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres18-pvc
  namespace: rahmapostgres18

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: manual
